### PR TITLE
New Yoga options and fixed the torso coupling matrix

### PR DESCRIPTION
**Pull request by gabrielenava**
It is now possible to run the yoga demo in loop both on one foot and on two feet. It is also possible to specify the number of times the yoga demo is repeated. Tested on `iCubGenova04`.

### CODE REVIEW

**Comment by gabrielenava** [comment]
This [issue](https://github.com/robotology/whole-body-controllers/issues/45) has also been fixed with this PR.

@lrapetti can you please double check this [commit](https://github.com/robotology/whole-body-controllers/pull/46/commits/744677118d0f30f040f90ff36cdabf7306aded86) before merging the PR? Thanks!

**Comment by lrapetti** [comment]
> This [issue](https://github.com/robotology/whole-body-controllers/issues/45) has also been fixed with this PR.
> 
> @lrapetti can you please double check this [commit](https://github.com/robotology/whole-body-controllers/pull/46/commits/744677118d0f30f040f90ff36cdabf7306aded86) before merging the PR? Thanks!

@gabrielenava 

@FabioBergonti this afternoon showed me an error that was still present in the matrix presented in the [issue](https://github.com/robotology/whole-body-controllers/issues/45#issue-367258039). We corrected it but probably you already copied the values.

The matrix you used for the commit is wrong. The correct matrix is:
```
T_torso = [0.5     -0.5     0;
            0.5     0.5     0;
            r/(2*R) r/(2*R) r/R];
```

**Comment by gabrielenava** [comment]
@lrapetti  I modified again the coupling matrix, this time it should be correct.

**Comment by lrapetti** [comment]
> @lrapetti I modified again the coupling matrix, this time it should be correct.

Yes, now it should be right.

**Pull request merged**
