### PR TITLE
WBC release 2.5.2

### LINKED ISSUE #94: Whole-body-controllers release 2.5.2
## RELEASE DATE: TBD

This issue is a tracker for the new WBC release 2.5.2.

Issues involved in the new release (list will be updated in the future):

~- [ ] [Fix bug in fromTransfMatrixToPosQuat](https://github.com/robotology/whole-body-controllers/issues/111)~
~- [ ] [Add KPI logic to evaluate performance and robustness of controllers](https://github.com/robotology/whole-body-controllers/issues/96)~
~- [ ] [Change the name of the repo](#109)~
- [X] [Added Momentum Based Velocity control as a new WBC Simulink library](#99 )
- [x] Update documentation for release 2.5.2
~- [ ] [Understand how to create standalone Simulink applications](https://github.com/robotology/whole-body-controllers/issues/91)~
~- [ ] [Implement a block to check if the measured forces violate the contact constraints](https://github.com/robotology/whole-body-controllers/issues/89)~
~- [ ] [Implement github actions](https://github.com/robotology/whole-body-controllers/issues/88)~
- [x] [Migrate the jerk control in whole-body-controllers](https://github.com/robotology/whole-body-controllers/issues/87)
~- [ ] [Simplify the simulation pipeline](https://github.com/robotology/whole-body-controllers/issues/76)~
~- [ ] [Import functions and remove deprecated in the WBC library](https://github.com/robotology/whole-body-controllers/issues/71)~
- [x] [Improve the Simulink-balancing-simulator](https://github.com/robotology/whole-body-controllers/issues/95)
~- [ ] [Create the controllers library with its first block: the YOGA++ controller](https://github.com/robotology/whole-body-controllers/issues/114)~
~- [ ] [Create a library of controller blocks out of the multiple models in this repo and integrate them in those models](https://github.com/robotology/whole-body-controllers/issues/113)~

### PR DESCRIPTION
**Pull request by gabrielenava**
See the associated issue: #94 

cc @nunoguedelha

### CODE REVIEW

**Comment by traversaro** [comment]
@gabrielenava can we release this version of whole-body-controllers without waiting for all the features listed in https://github.com/robotology/whole-body-controllers/issues/94, or  do you think there could be problems? For several internal issues it would be great to get this out (i.e. released, inside a conda package) soon, thanks!

**Comment by gabrielenava** [comment]
>@gabrielenava can we release this version of whole-body-controllers without waiting for all the features listed in #94, or do you think there could be problems? For several internal issues it would be great to get this out (i.e. released, inside a conda package) soon, thanks!

I think it is ok, the only issue it may be worth to address now is the documentation update https://github.com/robotology/whole-body-controllers/issues/90, just to ensure that all changes and features are correctly documented

**Comment by traversaro** [comment]
> 
> 
> > @gabrielenava can we release this version of whole-body-controllers without waiting for all the features listed in #94, or do you think there could be problems? For several internal issues it would be great to get this out (i.e. released, inside a conda package) soon, thanks!
> 
> I think it is ok, the only issue it may be worth to address now is the documentation update #90, just to ensure that all changes and features are correctly documented

Ok, @nunoguedelha do you think it is feasible? Which part of the documentation need to be updated?

**Comment by nunoguedelha** [comment]
Well, actually #90 it's the **only** thing missing from #94 right?

>- describe briefly the theory behind each controller (math + diagrams) and add reference for detailed description

>Possible advice:

> - describe how to tune the CoM and joints gains for the yoga demo
> - describe how to tune the regularization parameters for the yoga demo

I think this can be too long if we want to trigger the release tomorrow. And I think it wouldn't be a big deal to leave such thorough documentation for the following release.

I was targeting to submit the PR documenting the YOGA+matlab-whole-body-simulator before tomorrow morning (your time), plus the merges to master, such that we put the tags.

**Comment by nunoguedelha** [comment]
So basically, to be clear, I think we should do this merge after #126 where I'm documenting the stuff from the new model (YOGA+mwbs).

**Comment by traversaro** [comment]
Thanks, I did not noticed #90 was so complex, probably we can do a release even without all of #90 ? @gabrielenava

**Comment by traversaro** [comment]
> 
> 
> Thanks, I did not noticed #90 was so complex, probably we can do a release even without all of #90 ? @gabrielenava

To clarify, we can mark the new release of 2.6 or something like that, and then leave for 3.0 the revamped docs, the rename, etc etc.

**Comment by gabrielenava** [comment]
>Thanks, I did not noticed #90 was so complex, probably we can do a release even without all of #90 ? @gabrielenava

I did not remember either that the target of #90 was so high, with

>I think it is ok, the only issue it may be worth to address now is the documentation update #90, just to ensure that all changes and features are correctly documented

I just meant what @nunoguedelha wrote in https://github.com/robotology/whole-body-controllers/pull/115#issuecomment-837375644 plus a general check to verify that all readmes and wiki are updated.  

>To clarify, we can mark the new release of 2.6 or something like that, and then leave for 3.0 the revamped docs, the rename, etc etc.

Ok to me,  I made already a pre-release ([2.5.1](https://github.com/robotology/whole-body-controllers/releases/tag/v2.5.1)), is it fine to call this release `2.5.2`?

**Comment by traversaro** [comment]
> Ok to me, I made already a pre-release (2.5.1), is it fine to call this release 2.5.2?

Ok for me, @nunoguedelha ?

**Comment by nunoguedelha** [comment]
Fine to me. So we agree that #126 goes first? I'm about to finish that one...

**Comment by traversaro** [comment]
> 
> 
> Fine to me. So we agree that #126 goes first? I'm about to finish that one...

Yes.

**Comment by nunoguedelha** [comment]
#126 is merged on devel. We can proceed with this one. We create a merge commit, or do a fast-forward of master? @gabrielenava @traversaro

**Comment by nunoguedelha** [comment]
It seems, from the commits tree history of the repo, that the common practice here is to fast-forward the master. Am I right @gabrielenava ?

**Comment by nunoguedelha** [comment]
@gabrielenava , I've done a fast-forward merge, such that you just have to apply the tag `v2.5.2` on `master`.

**Comment by nunoguedelha** [comment]
@gabrielenava , since we had clearly agreed on the release, I allowed myself to rename the PR to WBC release 2.5.2. Hope you don't mind. Also reopened #94 since there is still the documentation to do. See you tomorrow.

**Pull request merged**
