### PR TITLE
Reflect matlab-whole-body-simulator#49 (removal of dependency from +wbc)

### PR DESCRIPTION
**Pull request by nunoguedelha**
The changes are:
- Update model **floatingBaseBalancingTorqueControlWithSimulator** w.r.t. the PR  https://github.com/dic-iit/matlab-whole-body-simulator/pull/49 (remove dependency from `+wbc`)
- Update model **floatingBaseBalancingTorqueControlWithSimulator** w.r.t. the PR https://github.com/robotology/wb-toolbox/pull/211 :
    - Restore the link of the 'holder' blocks in the controller model to the
      WBToolbox (utilities) library -> after the new holder implementation was
      (https://github.com/robotology/wb-toolbox/pull/211).
    - Remove the 'holder' block (not required anymore) from the 'utilityBlocks_lib.slx'
      library.

### CODE REVIEW

**Comment by nunoguedelha** [comment]
CC @traversaro @CarlottaSartore

**Comment by nunoguedelha** [comment]
It makes sense to ad also @Giulero as a reviewer since he's already testing the controllers used on **ironCub** against the replacement of the "Holder" blocks.

**Comment by nunoguedelha** [comment]
This branch will need to be rebased on top of `devel` but it's a trivial one.

**Comment by Giulero** [comment]
@nunoguedelha I tested the `torqueControlBalancingWithSimu.mdl` model and everything went ok. Do you want me to do other tests?

**Review by traversaro — APPROVED** [review]

**Comment by nunoguedelha** [comment]
> @nunoguedelha I tested the `torqueControlBalancingWithSimu.mdl` model and everything went ok. Do you want me to do other tests?

Great @Giulero , regarding the tests it's enough. Thanks!

**Review by Giulero — APPROVED** [review]

**Comment by nunoguedelha** [comment]
Merged. CC @gabrielenava

**Pull request merged**
