### PR TITLE
New QP implementation through WBToolbox block

### PR DESCRIPTION
**Pull request by gabrielenava**
I removed the [S-function](https://github.com/robotology/whole-body-controllers/blob/master/torque-controllers/momentum-based-yoga/src/QPBalancingYoga.m) that contained the call to QPOASES and I added utility functions for using the new `QP` block from WBToolbox instead. At the moment, the usage of the WBToolbox `QP` block is a **must** if we want to auto-generate the C++ code from Simulink using `Simulink coder`. 

**Warning:** The behavior of the controller is **not the same as before**! In fact now **as soon as the QP fails, the Simulink controller stops**, exiting with an error as follows (exitFlagQP = -2 --> failure):

screenshot from 2018-08-22 16-26-22

screenshot from 2018-08-22 16-50-08

My question is: is this behavior desirable?

- on one hand, this make sense on the real robot: if the QP fails, stop the robot and revert to position control.

- on the other hand, all the controllers are not working anymore in simulation with both `icubGazeboSim` and `iCubGazeboV2_5`. This because during contact switching there are always few instants where the QP fails. This happens both during the standup and during the yoga on both feet (when switching from 1 foot to 2 feet balancing). I do not remember if this happens also on the real robot, however in order to get rid of this behavior we (probably, I am not sure) need to perform gain and parameters tuning. I don't know if it makes sense to tune the Yoga and the Standup demo in simulation at this stage. 

What do you think @DanielePucci @diegoferigo @S-Dafarra @traversaro @Yeshasvitvs?

### CODE REVIEW

**Comment by S-Dafarra** [comment]
I think that the ``QP`` failure should not be blocking for the Simulink controller unless the user chooses so. Is it possible to add this as option @diegoferigo?

**Comment by traversaro** [comment]
In the past version of the controller, if the QP failed, which solution was used instead in the controller?

**Comment by gabrielenava** [comment]
>In the past version of the controller, if the QP failed, which solution was used instead in the controller?

The analytical solution of the minimization problem without the constraints, namely [this](https://github.com/robotology/whole-body-controllers/pull/36/commits/f33a433401ec062ed2ca45bce16c0efc35230be8#diff-06dc11c96b1ce0b9609eec2c7e1db5a2R3)

**Update** I discover there is already an option for avoiding to stop the simulation when the QP fails:

screenshot from 2018-08-22 17-20-17

But it was already unchecked. Checking it also stops the controller. I think I will open a separate issue for this.

**Comment by traversaro** [comment]
> The analytical solution of the minimization problem without the constraints, namely this

So, in a general  QP solver context, this would mean that you would like to get the **unconstrained solution** if the QP fails, right?

**Comment by traversaro** [comment]
I guess you need to modify https://github.com/robotology/wb-toolbox/blob/ce58905b3aa5eb2b6f19da800f52fff9202290a6/toolbox/library/src/QpOases.cpp#L490 to get the desired behavior. Apparently that option only affects failures in initialization (https://github.com/robotology/wb-toolbox/blob/ce58905b3aa5eb2b6f19da800f52fff9202290a6/toolbox/library/src/QpOases.cpp#L446) or hotStart (https://github.com/robotology/wb-toolbox/blob/ce58905b3aa5eb2b6f19da800f52fff9202290a6/toolbox/library/src/QpOases.cpp#L481).

**Comment by gabrielenava** [comment]
>So, in a general QP solver context, this would mean that you would like to get the unconstrained solution if the QP fails, right?

At least for the Yoga and Standup demos. But there are different possibilities, for example in [the QP controller for walking](https://github.com/gabrielenava/whole-body-controllers/blob/master/torque-controllers/task-based-walking/src/controller/QPBalancingMPC.m#L321) we implemented a different behavior: if the QP fails, then keep the solution calculated in the previous integration step.  Anyway the "ideal" implementation for me is the following:

- An option in the `QP` block so that I can choose, in case of QP failures, either to stop the simulation or to output a "default" value (can be a vector of zeros, or the unconstrained solution, or whatever. Just let me know what the output is). 

- Then, I can eventually overwrite the "default" output in case of QP failures from the Simulink model.

**Comment by DanielePucci** [comment]
Agree with @gabrielenava

**Comment by gabrielenava** [comment]
This PR fixed the issue: https://github.com/robotology/wb-toolbox/pull/159

Waiting for the merge, then we can merge also this PR.

**Pull request merged**
