### PR TITLE
Update README (after #122)

### PR DESCRIPTION
**Pull request by nunoguedelha**

### CODE REVIEW

**Comment by nunoguedelha** [comment]
Follow-up of #122 :

@gabrielenava 
> - [x] Could you add `matlab-whole-body-simulator` also to the list of dependencies in the [main WBC readme](https://github.com/robotology/whole-body-controllers/tree/feature/replace-gazebo-by-matlab-simulator#dependencies), and specify that it is an optional dependency for Gazebo-free simulations?
> 
> - [x] Also, feel free to remove the previous [simulink-balancing simulator](https://github.com/robotology/whole-body-controllers/blob/feature/replace-gazebo-by-matlab-simulator/controllers/simulink-balancing-simulator/README.md), also from the [list of available controllers](https://github.com/robotology/whole-body-controllers/tree/feature/replace-gazebo-by-matlab-simulator#available-controllers) (and to add instead your simulator).
> - [x] We can add the `simulink-balancing-simulator` to the list of [legacy controllers](https://github.com/robotology/whole-body-controllers#where-do-i-find-legacy-materials) in the README, in the past I moved old controllers in [WBI-Toolbox-Controllers](https://github.com/robotology-legacy/WBI-Toolbox-controllers) but in this case maybe it is just sufficient to point the last commit where the `simulink-balancing simulator` is still present.

@traversaro 
> - [x] Why do we need to set manually setenv('YARP_ROBOT_NAME','iCubGazeboV2_5') ? Can't we set it somewhere in the example initialization or similar?
> - [x] Could we install torqueControlBalancingWithSimu.mdl, perhaps in a matlab/examples directory or similar? ...

ONGOING...
(the package `+floatingBaseBalancingTorqueControlWithSimulator` just needs to be copied to the install folder `mex/examples` and `mex/examples` needs to be added t MATLABPATH the same way as `mex/simulink`.

By the way it's a bit complex the installation framework there...

**Comment by traversaro** [comment]
> By the way it's a bit complex the installation framework there...

In which sense? Can't we add a `install(DIRECTORY ...)` and `install(FILES ..)` and add the files that we need to install where we need to install them?

**Comment by nunoguedelha** [comment]
> Can't we add a `install(DIRECTORY ...)` and `install(FILES ..)` a

Yes, I ended up chosing that. Initially I was trying to follow the local `whole-body-controllers` pattern, but I'll just go with the `install(DIRECTORY ...)` and `install(FILES ..)` etc ...

**Comment by nunoguedelha** [comment]
The installation is handled and tested. Had t choose a not so clean and elegant solution due to the logic around the automatic code generation handled in the main `CMakeLists.txt`. I'm just checking now the Conda scripts...

**Comment by traversaro** [comment]
> 
> 
> The installation is handled and tested. Had t choose a not so clean and elegant solution due to the logic around the automatic code generation handled in the main `CMakeLists.txt`. I'm just checking now the Conda scripts...

Can we mark the PR as ready in the meanwhile? So we can review and release it, and if more problem arise we can fix them later.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
As this PR is targeted on master, I guess it supersedes https://github.com/robotology/whole-body-controllers/pull/115 ?

**Comment by nunoguedelha** [comment]
no, no, sorry, I had rebased on devel and forgot to change the target here. It's targeted on `devel`.

**Comment by nunoguedelha** [comment]
there were some templates missing, along with multisheller scripts updates. Pushing now..

**Comment by nunoguedelha** [comment]
> there were some templates missing, along with multisheller scripts updates. Pushing now..

nonsense! those are robotology-superbuild changes.

**Comment by nunoguedelha** [comment]
Merging...

**Pull request merged**
