### PR TITLE
Integrate the YOGA++ (floating-base-balancing-torque-control) with the matlab-whole-body-simulator

### PR DESCRIPTION
**Pull request by nunoguedelha**
Implements #121 .

### CODE REVIEW

**Comment by nunoguedelha** [comment]
## How to test this PR
- Install the superbuild as usual, lates release (`LatestRelease` set to `LatestRelease`).
- in `src/matlab-whole-body-simulator` checkout `devel`.
- re-install `matlab-whole-body-simulator` target.
- in `whole-body-controllers` set working directory `src/whole-body-controllers/controllers/floating-base-balancing-torque-control-with-simulator`
- open model `torqueControlBalancingWithSimu.mdl`
- set robot model `setenv('YARP_ROBOT_NAME','iCubGazeboV2_5')`
- run

**Comment by nunoguedelha** [comment]
@traversaro @gabrielenava , the PR is ready for review.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @nunoguedelha , two comments: 
* Could we install `torqueControlBalancingWithSimu.mdl`, perhaps in a `matlab/examples` directory or similar? In this way the example is available also for people that install `whole-body-controllers` via conda, otherwise if the use need to know how to use git to download the examples we would lose the main advantage of a one line installation.
* Why do we need to set manually `setenv('YARP_ROBOT_NAME','iCubGazeboV2_5')` ? Can't we set it somewhere in the example initialization or similar?

**Comment by gabrielenava** [comment]
Tested following https://github.com/robotology/whole-body-controllers/pull/122#issuecomment-834541660 on my PC with Ubuntu 20.04 LTS.

Seems working fine:
image

I've found it a bit slow in the `initializing` and `terminating` processes, is it normal? The simulation instead was running with a quite good update rate.

A couple of comments:

- Could you add `matlab-whole-body-simulator` also to the list of dependencies in the [main WBC readme](https://github.com/robotology/whole-body-controllers/tree/feature/replace-gazebo-by-matlab-simulator#dependencies), and specify that it is an optional dependency for Gazebo-free simulations? 

- Also, feel free to remove the previous [simulink-balancing simulator](https://github.com/robotology/whole-body-controllers/blob/feature/replace-gazebo-by-matlab-simulator/controllers/simulink-balancing-simulator/README.md), also from the [list of available controllers](https://github.com/robotology/whole-body-controllers/tree/feature/replace-gazebo-by-matlab-simulator#available-controllers) (and to add instead your simulator). We can add the `simulink-balancing-simulator` to the list of [legacy controllers](https://github.com/robotology/whole-body-controllers#where-do-i-find-legacy-materials) in the README, in the past I moved old controllers in [WBI-Toolbox-Controllers](https://github.com/robotology-legacy/WBI-Toolbox-controllers) but in this case maybe it is just sufficient to point the last commit where the `simulink-balancing simulator` is still present.

**Review by gabrielenava — APPROVED** [review]

**Comment by nunoguedelha** [comment]
Sure @gabrielenava , I'll do a mini-PR to update the documentation covering all the points you've listed. Thanks.

**Comment by nunoguedelha** [comment]
> Thanks @nunoguedelha , two comments:
> 
>     * Could we install `torqueControlBalancingWithSimu.mdl`, perhaps in a `matlab/examples` directory or similar? In this way the example is available also for people that install `whole-body-controllers` via conda, otherwise if the use need to know how to use git to download the examples we would lose the main advantage of a one line installation.
> 
>     * Why do we need to set manually `setenv('YARP_ROBOT_NAME','iCubGazeboV2_5')` ? Can't we set it somewhere in the example initialization or similar?

and addressing this too @traversaro .
> Could we install `torqueControlBalancingWithSimu.mdl`,

Yes indeed.

> Why do we need to set manually ...

It makes usually sense to set it separately when there are several models. It makes also sense to have a working model set by default, and right now `iCubGazeboV2_5` is the only one, so I'll add the setting of a default `YARP_ROBOT_NAME = iCubGazeboV2_5` in the model initialization as you suggested.

**Comment by nunoguedelha** [comment]
> I've found it a bit slow in the `initializing` and `terminating` processes, is it normal? The simulation instead was running with a quite good update rate.

It's slow for me too. Probably because there are more sub-systems treated as atomic blocks (the cntroller, the simulator, the visualizer), which results in more code generation, which is slower at compilation but faster at runtime.

**Pull request merged**
