### PR TITLE
Fix link to floating-base-balancing-torque-control-with-simulator in controllers directory README

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Review by nunoguedelha — APPROVED** [review]

**Review by gabrielenava — COMMENTED** [review]
I tried and it didn't work for me, but I don't know if it is because the fix in a branch and not in `master`

**Comment by traversaro** [comment]
> I tried and it didn't work for me, but I don't know if it is because the fix in a branch and not in `master`

In which sense? In master it does not work, this is the reason I did the PR. If you click in https://github.com/robotology/whole-body-controllers/tree/fixcontrolreadme/controllers it does not work?

**Comment by gabrielenava** [comment]
Apparently I was in the correct branch but I clicked on the link in the main README: https://github.com/robotology/whole-body-controllers/tree/fixcontrolreadme#available-controllers

Not the one in the `controllers` folder. I don't know if the link in the main readme also needs to be updated, or it is not supposed to work if not in `master`

image

**Comment by traversaro** [comment]
I fixed also the link in the main README.

**Review by gabrielenava — APPROVED** [review]

**Comment by traversaro** [comment]
@gabrielenava friendly ping

**Comment by gabrielenava** [comment]
working now, I merge the PR!

**Pull request merged**
